version: 0.2

env:
  parameter-store:
    GH_TOKEN: "/parameter-manager/prod/githubtoken"

phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run-script make -- --platform="linux" --asar="false"
      - npm run-script make -- --platform="win32" --asar="true"
artifacts:
  files:
    - 'make/**/*'
  discard-paths: yes
  base-directory: out
